"""Atomic, checksummed PPO + VecNormalize checkpoint bundles.

Only ``checkpoints/step-N[-final]/manifest.json`` marks a published bundle. Copying to
``mirror_dir`` is a filesystem mirror, NOT evidence of off-instance backup.
An external verifier may write ``backup_receipt.json`` beside the manifest:
``{"verified": true, "manifest_sha256": "...", "destination": "..."}``.
The receipt is an operator assertion, not a cryptographic proof of location.
"""
from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json
import math
import os
from pathlib import Path
import shutil
import tempfile
import time

from stable_baselines3.common.callbacks import BaseCallback

BUNDLE_FILES = ("model.zip", "vecnormalize.pkl", "train_config.json")


def sha256_file(path: Path | str) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_json(path: Path | str, value: dict) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(value, handle, indent=2, sort_keys=True, allow_nan=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        # This is only the exact file generated by mkstemp above.
        if os.path.isfile(temporary):
            os.unlink(temporary)


def verify_checkpoint_bundle(bundle: Path | str) -> dict:
    bundle = Path(bundle)
    manifest = json.loads((bundle / "manifest.json").read_text(encoding="utf-8"))
    if manifest.get("schema_version") != 1 or manifest.get("complete") is not True:
        raise ValueError(f"Incomplete or unsupported checkpoint manifest: {bundle}")
    if set(manifest.get("files", {})) != set(BUNDLE_FILES):
        raise ValueError("Checkpoint must contain exactly the paired model, normalizer and config")
    for name in BUNDLE_FILES:
        path = bundle / name
        metadata = manifest["files"][name]
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Missing or unsafe checkpoint file: {path}")
        if path.stat().st_size != metadata["bytes"] or sha256_file(path) != metadata["sha256"]:
            raise ValueError(f"Checkpoint checksum mismatch: {path}")
    return manifest


def save_checkpoint_bundle(model, normalizer, run_dir: Path | str, config: dict,
                           final: bool = False) -> Path:
    """Save a new complete bundle without overwriting any existing step."""
    if normalizer is None:
        raise ValueError("A paired VecNormalize is required for safe walker checkpoints")
    run_dir = Path(run_dir)
    checkpoint_dir = run_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    step = int(model.num_timesteps)
    if step < 0:
        raise ValueError("Checkpoint step must be non-negative")
    bundle_name = f"step-{step}" + ("-final" if final else "")
    destination = checkpoint_dir / bundle_name
    if destination.exists():
        raise FileExistsError(f"Refusing to overwrite checkpoint: {destination}")
    temporary = Path(tempfile.mkdtemp(prefix=f".step-{step}.incomplete-", dir=checkpoint_dir))
    # Failed staging directories are deliberately retained for diagnosis. They
    # never match step-* and must never be consumed by a backup pull worker.
    model.save(str(temporary / "model.zip"))
    normalizer.save(str(temporary / "vecnormalize.pkl"))
    atomic_json(temporary / "train_config.json", config)
    files = {}
    for name in BUNDLE_FILES:
        path = temporary / name
        # Windows FlushFileBuffers requires a writable descriptor; r+b does
        # not alter the bytes, and also works with POSIX fsync.
        with path.open("r+b") as handle:
            os.fsync(handle.fileno())
        files[name] = {"sha256": sha256_file(path), "bytes": path.stat().st_size}
    atomic_json(temporary / "manifest.json", {
        "schema_version": 1, "complete": True, "num_timesteps": step,
        "stage": "final" if final else "checkpoint",
        "created_utc": datetime.now(timezone.utc).isoformat(), "files": files,
        "resume_semantics": "model+optimizer+normalization; not exact simulator/RNG continuation",
    })
    # rename is atomic on the same filesystem; refusing an existing destination
    # protects earlier bundles instead of replacing their contents.
    temporary.rename(destination)
    verify_checkpoint_bundle(destination)
    atomic_json(run_dir / "latest_checkpoint.json", {
        "schema_version": 1, "num_timesteps": step,
        "bundle": f"checkpoints/{bundle_name}",
        "manifest_sha256": sha256_file(destination / "manifest.json"),
    })
    return destination


def export_legacy_final(bundle: Path | str, run_dir: Path | str) -> None:
    """Compatibility aliases; the checksummed bundle is the authoritative pair.

    ``final_manifest.json`` is published only after both aliases exist. Consumers
    requiring transactional pairing should load directly from the bundle.
    """
    bundle, run_dir = Path(bundle), Path(run_dir)
    manifest = verify_checkpoint_bundle(bundle)
    for source, alias in (("model.zip", "final.zip"), ("vecnormalize.pkl", "vecnormalize.pkl")):
        destination = run_dir / alias
        if destination.exists():
            raise FileExistsError(f"Refusing to overwrite final alias: {destination}")
        fd, temporary = tempfile.mkstemp(prefix=f".{alias}.", dir=run_dir)
        os.close(fd)
        shutil.copy2(bundle / source, temporary)
        os.replace(temporary, destination)
    atomic_json(run_dir / "final_manifest.json", {
        "schema_version": 1, "num_timesteps": manifest["num_timesteps"],
        "bundle": str(bundle.relative_to(run_dir)).replace("\\", "/"),
        "manifest_sha256": sha256_file(bundle / "manifest.json"),
        "aliases": {"final.zip": manifest["files"]["model.zip"],
                    "vecnormalize.pkl": manifest["files"]["vecnormalize.pkl"]},
    })


def mirror_checkpoint_bundle(bundle: Path | str, mirror_dir: Path | str) -> Path:
    """Copy and verify a bundle. Caller must establish whether storage is remote."""
    bundle, mirror_dir = Path(bundle).resolve(), Path(mirror_dir).resolve()
    verify_checkpoint_bundle(bundle)
    mirror_dir.mkdir(parents=True, exist_ok=True)
    destination = mirror_dir / bundle.parent.parent.name / bundle.name
    if destination == bundle or bundle in destination.parents:
        raise ValueError("Mirror must be outside the source bundle")
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        verify_checkpoint_bundle(destination)
        if sha256_file(destination / "manifest.json") != sha256_file(bundle / "manifest.json"):
            raise FileExistsError(f"Mirror has a conflicting checkpoint: {destination}")
        return destination
    temporary = Path(tempfile.mkdtemp(prefix=f".{bundle.name}.incomplete-", dir=destination.parent))
    for name in (*BUNDLE_FILES, "manifest.json"):
        shutil.copy2(bundle / name, temporary / name)
    verify_checkpoint_bundle(temporary)
    temporary.rename(destination)
    return destination


def wait_for_backup_receipt(bundle: Path | str, timeout_seconds: float) -> dict:
    """Fail closed if the external verified-backup acknowledgement is absent."""
    if not math.isfinite(timeout_seconds) or timeout_seconds <= 0:
        raise ValueError("Backup acknowledgement timeout must be finite and positive")
    bundle = Path(bundle)
    expected = sha256_file(bundle / "manifest.json")
    deadline = time.monotonic() + timeout_seconds
    while True:
        receipt_path = bundle / "backup_receipt.json"
        if receipt_path.exists():
            try:
                receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                receipt = {}
            if (receipt.get("verified") is True
                    and receipt.get("manifest_sha256") == expected
                    and isinstance(receipt.get("destination"), str)
                    and receipt["destination"].strip()):
                return receipt
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise TimeoutError(f"Verified off-instance backup acknowledgement missing: {bundle}")
        time.sleep(min(0.25, remaining))


class CheckpointBundleCallback(BaseCallback):
    """Publish at start, every N aggregate env steps, and training completion.

    Initial acknowledgement is a preflight barrier when enabled: no learning
    starts until the external backup verifier acknowledges the initial bundle.
    An acknowledgement is required again for each subsequent saved bundle.
    The optional wall limit stops at the next callback; it is not an EC2 stop
    timer and does not bound long initialization, updates, or evaluation calls.
    """
    def __init__(self, run_dir, config, checkpoint_freq=100_000,
                 max_wall_seconds=None, mirror_dir=None, require_backup_ack=False,
                 backup_ack_timeout=120.0, verbose=1):
        super().__init__(verbose)
        if int(checkpoint_freq) != checkpoint_freq or checkpoint_freq <= 0:
            raise ValueError("checkpoint_freq must be a positive integer")
        if max_wall_seconds is not None and (not math.isfinite(max_wall_seconds) or max_wall_seconds <= 0):
            raise ValueError("max_wall_seconds must be finite and positive")
        if not math.isfinite(backup_ack_timeout) or backup_ack_timeout <= 0:
            raise ValueError("backup_ack_timeout must be finite and positive")
        self.run_dir, self.config = Path(run_dir), dict(config)
        self.checkpoint_freq = int(checkpoint_freq)
        self.max_wall_seconds = max_wall_seconds
        self.mirror_dir = mirror_dir
        self.require_backup_ack = bool(require_backup_ack)
        self.backup_ack_timeout = backup_ack_timeout
        self.last_bundle = None
        self._saved_step = None
        self._next_step = 0
        self._start_time = None
        self.stopped_for_wall_limit = False

    def save_now(self, final: bool = False) -> Path:
        step = int(self.model.num_timesteps)
        if self._saved_step == (step, final):
            return self.last_bundle
        bundle = save_checkpoint_bundle(
            self.model, self.model.get_vec_normalize_env(), self.run_dir, self.config,
            final=final,
        )
        self._saved_step, self.last_bundle = (step, final), bundle
        print(f"[checkpoint] published={bundle} steps={step}", flush=True)
        if self.mirror_dir:
            mirrored = mirror_checkpoint_bundle(bundle, self.mirror_dir)
            print(f"[checkpoint] filesystem_mirror={mirrored} (off-instance location not asserted)", flush=True)
        if self.require_backup_ack:
            print(f"[checkpoint] waiting_for_backup_ack={bundle}", flush=True)
            acknowledgement_timeout = self.backup_ack_timeout
            if self.max_wall_seconds is not None and self._start_time is not None:
                remaining = self.max_wall_seconds - (time.monotonic() - self._start_time)
                if remaining <= 0:
                    raise TimeoutError(f"Wall limit reached before backup acknowledgement: {bundle}")
                acknowledgement_timeout = min(acknowledgement_timeout, remaining)
            wait_for_backup_receipt(bundle, acknowledgement_timeout)
            print(f"[checkpoint] backup_ack_verified={bundle}", flush=True)
        return bundle

    def _on_training_start(self) -> None:
        self._start_time = time.monotonic()
        self._next_step = (int(self.model.num_timesteps) // self.checkpoint_freq + 1) * self.checkpoint_freq
        self.save_now()

    def _on_step(self) -> bool:
        if self.model.num_timesteps >= self._next_step:
            self.save_now()
            self._next_step = (int(self.model.num_timesteps) // self.checkpoint_freq + 1) * self.checkpoint_freq
        if (self.max_wall_seconds is not None and self._start_time is not None
                and time.monotonic() - self._start_time >= self.max_wall_seconds):
            self.stopped_for_wall_limit = True
            print("[checkpoint] wall limit reached; stopping learning safely", flush=True)
            return False
        return True

    def _on_training_end(self) -> None:
        # PPO's final optimizer update can follow a periodic checkpoint at the
        # same step. A distinct immutable bundle captures those final weights.
        self.save_now(final=True)
